language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-testing.txt
# command to run tests
script: nosetests -v --with-coverage --cover-tests --cover-package=toast
